alias zeus="OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES bin/zeus start"
alias dbupdate="bin/rake db:migrate db:test:prepare"
alias nbrt="notify bin/rails test $@"
alias cdspcs="ghcs ssh --profile github-codespaces"
alias ibrew="arch -x86_64 /usr/local/bin/brew"
alias mbrew="arch -arm64 /opt/homebrew/bin/brew"
